# fly.toml app configuration file generated for puppy-tracker-zxjfow on 2026-06-22T10:22:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'puppy-tracker-zxjfow'
primary_region = 'arn'

[build]

[env]
  DATABASE_PATH = '/data/puppy.db'
  TZ = 'Europe/Oslo'

[[mounts]]
  source = 'puppy_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
